// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXv9vz9RLdq3FegFYYQLDmc-KhyUpiU9o',
    appId: '1:245681407428:web:abcdef123456', // 웹 앱 등록 시 Firebase 콘솔에서 업데이트 필요
    messagingSenderId: '245681407428',
    projectId: 'stepping-stone-game',
    authDomain: 'stepping-stone-game.firebaseapp.com',
    storageBucket: 'stepping-stone-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy1PfgQNIqB6SNvNNTH80FSWWCHDjO-jw',
    appId: '1:245681407428:android:846ad13b0c02930ceb1091',
    messagingSenderId: '245681407428',
    projectId: 'stepping-stone-game',
    storageBucket: 'stepping-stone-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXv9vz9RLdq3FegFYYQLDmc-KhyUpiU9o',
    appId: '1:245681407428:ios:abcdef123456', // Firebase 콘솔에서 확인 필요
    messagingSenderId: '245681407428',
    projectId: 'stepping-stone-game',
    storageBucket: 'stepping-stone-game.firebasestorage.app',
    iosClientId: '245681407428-quouf9v7hph8t9g7hainp7fu5731dh6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.webviewGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXv9vz9RLdq3FegFYYQLDmc-KhyUpiU9o',
    appId: '1:245681407428:macos:abcdef123456', // Firebase 콘솔에서 확인 필요
    messagingSenderId: '245681407428',
    projectId: 'stepping-stone-game',
    storageBucket: 'stepping-stone-game.firebasestorage.app',
    iosClientId: '245681407428-quouf9v7hph8t9g7hainp7fu5731dh6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.webviewGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXv9vz9RLdq3FegFYYQLDmc-KhyUpiU9o',
    appId: '1:245681407428:windows:abcdef123456', // Firebase 콘솔에서 확인 필요
    messagingSenderId: '245681407428',
    projectId: 'stepping-stone-game',
    storageBucket: 'stepping-stone-game.firebasestorage.app',
  );
}

// ⚠️ 주의: Firebase 콘솔에서 다음 정보들을 확인하여 업데이트하세요:
// 1. 프로젝트 ID (project-id)
// 2. 앱 ID들 (app-id for Android/iOS/Web)  
// 3. 메시징 센더 ID (messaging-sender-id)
// 4. iOS 클라이언트 ID (ios-client-id)
// 
// 또는 다음 명령어로 자동 설정:
// flutterfire configure --project=[your-project-id]